name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with: 
        node-version: '15.x'
    - name: Assemble yml files
      run: |
        mkdir -p public/conference && cd public/conference
        awk 1 `find ../../conference -name '*.yml' -not -path '**/types.yml'` > allconf.yml
        cp ../../conference/types.yml .
        cd ../..
    - name: Install dependency and build
      run: |
        yarn install
        yarn build
    - name: Config Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions"
    - name: Deploy
      run: |
        cd dist
        git init
        git add --all
        git commit -m "Site Update:`TZ=':Asia/Shanghai' date +' %Y-%m-%d %H:%m:%S'`"
        git push --force https://${{ secrets.ACCESS_TOKEN }}@github.com/yzs981130/ddl_dist.git
